requiredParams:
  name: HeadHunter Feature API Base
  description: Creates HeadHunter Feature API Base

optionalParams:
  revision: 1
  category: fragment
  formFactor: mobile
  constraints:
    - kotlin
  screens:
    - fragment_gallery
    - menu_entry
  minApi: 7
  minBuildApi: 8

widgets:
  - stringParameter:
      id: feature
      name: Feature Name
      help: The name of the feature class to create
      constraints:
        - class
        - nonempty
        - unique
      default: Feature

globals:
  - stringParameter:
      id: featureApi
      value: ${feature}Api

  - stringParameter:
      id: featureDefScreen
      value: ${feature}NavScreen

  - stringParameter:
      id: featureDeps
      value: ${feature}Deps

  - stringParameter:
      id: featureFacade
      value: ${feature}Facade

  - stringParameter:
      id: featureModuleName
      value: ${feature}Module

recipe:
  - instantiateAndOpen:
      from: root/src/app_package/FeatureApi.kt.ftl
      to: ${srcOut}/api/${featureApi}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureApiImpl.kt.ftl
      to: ${srcOut}/api/${featureApi}Impl.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureDeps.kt.ftl
      to: ${srcOut}/api/${featureDeps}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureFacade.kt.ftl
      to: ${srcOut}/api/${featureFacade}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureModule.kt.ftl
      to: ${srcOut}/api/${featureModuleName}.kt