requiredParams:
  name: HeadHunter Empty Module
  description: Creates empty Gradle-module for general purposes

predefinedFeatures:
  - enableModuleCreationParams

widgets:
  - booleanParameter:
      id: needFeatureStructure
      name: Generate feature structure?
      help:
        Generates root packages - api (for feature facade), data (for network/database),
        feature (for domain logic/mvi), ui (for fragments/viewmodels)
      default: false

  - booleanParameter:
      id: needTests
      name: Add dependencies for tests?
      help: Adds typical test-framework dependencies
      default: false

  - booleanParameter:
      id: needRx
      name: Add Rx dependencies?
      help: Adds rx dependencies
      default: false

  - booleanParameter:
      id: needToothpick
      name: Add Toothpick?
      help: Adds Toothpick dependencies
      default: false

  - booleanParameter:
      id: needNetworkLibraries
      name: Add network libraries?
      help: Adds typical network dependencies (GSON, Retrofit)
      default: false

  - booleanParameter:
      id: needDbLibraries
      name: Add Room?
      help: Adds Room dependencies
      default: false

  - booleanParameter:
      id: needUiLibraries
      name: Add UI dependencies (BaseFragment + MVVM)?
      help: Adds typical view layer dependencies
      default: false

  - booleanParameter:
      id: needMvi
      name: Add MVI dependencies?
      help: Adds dependencies for MVI
      default: false


recipe:
  - mkDirs:
      - ${srcOut}

  - predicate:
      validIf: ${needUiLibraries}
      commands:
        - mkDirs:
            - ${resOut}:
                - layout
                - values
                - drawables

  - predicate:
      validIf: ${needFeatureStructure}
      commands:
        - mkDirs:
            - ${srcOut}:
                - api
                - data
                - feature
                - ui

  - instantiate:
      from: root/gitignore.ftl
      to: ${rootOut}/.gitignore

  - instantiateAndOpen:
      from: root/build.gradle.ftl
      to: ${rootOut}/build.gradle

  - instantiateAndOpen:
      from: root/README.md
      to: ${rootOut}/README.md

  - instantiate:
      from: root/proguard-rules.pro.ftl
      to: ${rootOut}/proguard-rules.pro

  - instantiate:
      from: root/src/main/AndroidManifest.xml.ftl
      to: ${manifestOut}/AndroidManifest.xml
