requiredParams:
  name: HeadHunter MVI Feature
  description: Creates HeadHunter MVI Feature

widgets:
  - stringParameter:
      id: featureName
      name: Mvi Name
      help: The name of the Mvi Feature class to create
      constraints:
        - class
        - nonempty
        - unique
      default: BaseMviFeature

globals:
  - stringParameter:
      id: featureEffect
      value: ${featureName}Effect

  - stringParameter:
      id: featureNews
      value: ${featureName}News

  - stringParameter:
      id: featureState
      value: ${featureName}State

  - stringParameter:
      id: featureWish
      value: ${featureName}Wish

  - stringParameter:
      id: featureActor
      value: ${featureName}Actor

  - stringParameter:
      id: featureBootstrapper
      value: ${featureName}Bootstrapper

  - stringParameter:
      id: featureNewsPublisher
      value: ${featureName}NewsPublisher

  - stringParameter:
      id: featureReducer
      value: ${featureName}Reducer

recipe:
  # elements
  - instantiateAndOpen:
      from: root/src/app_package/element/FeatureEffect.kt.ftl
      to: ${srcOut}/feature/element/${featureEffect}.kt
  - instantiateAndOpen:
      from: root/src/app_package/element/FeatureNews.kt.ftl
      to: ${srcOut}/feature/element/${featureNews}.kt
  - instantiateAndOpen:
      from: root/src/app_package/element/FeatureState.kt.ftl
      to: ${srcOut}/feature/element/${featureState}.kt
  - instantiateAndOpen:
      from: root/src/app_package/element/FeatureWish.kt.ftl
      to: ${srcOut}/feature/element/${featureWish}.kt
  # feature
  - instantiateAndOpen:
      from: root/src/app_package/Feature.kt.ftl
      to: ${srcOut}/feature/${featureName}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureActor.kt.ftl
      to: ${srcOut}/feature/${featureActor}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureBootstrapper.kt.ftl
      to: ${srcOut}/feature/${featureBootstrapper}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureNewsPublisher.kt.ftl
      to: ${srcOut}/feature/${featureNewsPublisher}.kt
  - instantiateAndOpen:
      from: root/src/app_package/FeatureReducer.kt.ftl
      to: ${srcOut}/feature/${featureReducer}.kt